#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use <%=PHP_NAMESPACE%>\Command\<%=APP_NAMESPACE%>\<%=COMMAND_NAME%>;

$application = new Application('<%=APPLICATION_NAME%>', '<%=APPLICATION_VERSION%>');
$application->add(new <%=COMMAND_NAME%>());
$application->run();