#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use <%=VENDOR_NAMESPACE_PHP%>\Commands\<%=COMMAND_CLASSNAME%>;

$application = new Application('<%=APP_NAME%>', '<%=APP_VERSION%>');
$application->add(new <%=COMMAND_CLASSNAME%>());
$application->run();