#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use <%=VENDOR_NAME%>\<%=APP_NAMESPACE%>\Command\<%=CLASS_COMMAND_NAMESPACE%>\<%=PHP_CLASSNAME%>;

$application = new Application('<%=APPLICATION_NAME%>', '<%=APPLICATION_VERSION%>');
$application->add(new <%=PHP_CLASSNAME%>());
$application->run();